### ISSUE TITLE
dist.ipfs.tech/kubo/versions down

### ISSUE THREAD

**Issue by jonmattgray** [ipfs/kubo#10529]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-update or dist.ipfs.tech

### Description

https://dist.ipfs.tech/kubo/versions seems to be down? For example, running `npm install -g kubo` returns the following error:
```
npm error code 1
npm error path /Users/jgray/.nvm/versions/node/v20.17.0/lib/node_modules/kubo
npm error command failed
npm error command sh -c node src/post-install.js
npm error https://dist.ipfs.tech/kubo/versions
npm error RequestError: read ECONNRESET
npm error     at ClientRequest.<anonymous> (/Users/jgray/.nvm/versions/node/v20.17.0/lib/node_modules/kubo/node_modules/got/dist/source/core/index.js:970:111)
npm error     at Object.onceWrapper (node:events:634:26)
npm error     at ClientRequest.emit (node:events:531:35)
npm error     at origin.emit (/Users/jgray/.nvm/versions/node/v20.17.0/lib/node_modules/kubo/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
npm error     at emitErrorEvent (node:_http_client:108:11)
npm error     at TLSSocket.socketErrorListener (node:_http_client:511:5)
npm error     at TLSSocket.emit (node:events:519:28)
npm error     at emitErrorNT (node:internal/streams/destroy:169:8)
npm error     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm error     at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20) {
npm error   code: 'ECONNRESET',
npm error   timings: {
npm error     start: 1727858248921,
npm error     socket: 1727858248921,
npm error     lookup: 1727858248923,
npm error     connect: 1727858248939,
npm error     secureConnect: undefined,
npm error     upload: undefined,
npm error     response: undefined,
npm error     end: undefined,
npm error     error: 1727858248956,
npm error     abort: undefined,
npm error     phases: {
npm error       wait: 0,
npm error       dns: 2,
npm error       tcp: 16,
npm error       tls: undefined,
npm error       request: undefined,
npm error       firstByte: undefined,
npm error       download: undefined,
npm error       total: 35
npm error     }
npm error   }
npm error }
```

**Comment by lidel** [comment]
@jonmattgray thanks for reporting. `dist.ipfs.tech` issue should be resolved.
ps. In future, if you seem issues with NPM package, the relevant repository is https://github.com/ipfs/npm-kubo
