### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by ViniciusFXavier** [ipfs/kubo#9339]
👉️ Please describe what you were doing when this error happened.

Open the program and got this error.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.23.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Initializing daemon...
Kubo version: 0.15.0
Repo version: 12
System version: amd64/windows
Golang version: go1.18.5
Error: old style datatstore config detected


    at errorTemplate (E:\IPFS\resources\app.asar\src\daemon\migration-prompt.js:78:49)
    at Object.loadWindow (E:\IPFS\resources\app.asar\src\daemon\migration-prompt.js:129:26)
    at startIpfsWithLogs (E:\IPFS\resources\app.asar\src\daemon\daemon.js:191:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async startDaemon (E:\IPFS\resources\app.asar\src\daemon\daemon.js:230:21)
    at async startIpfs (E:\IPFS\resources\app.asar\src\daemon\index.js:48:17)
    at async setupDaemon (E:\IPFS\resources\app.asar\src\daemon\index.js:116:3)
    at async run (E:\IPFS\resources\app.asar\src\index.js:85:5)
```

**Comment by SgtPooki** [comment]
Hey Kubo team, can one of you two help out an IPFS Desktop user whose config seems to invalid, or direct him where he needs to go?

**Comment by Jorropo** [comment]
@SgtPooki I think they need to run https://dist.ipfs.tech/#ipfs-ds-convert
to convert their datastore (or revert their datastore config change)
