### ISSUE TITLE
0.18.0-rc1: panic in webtransport.(*transport).Dial

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9516]
### Version

```Text
0.18.0-rc1
```

### Config

```json
default
```

### Description

Problem with kubo 0.18.0-rc1. At some point it crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1b589c7]

goroutine 284534 [running]:
github.com/libp2p/go-libp2p/p2p/transport/webtransport.(*transport).Dial(0xc000736580, {0x2ba5508, 0xc00a8a5ec0}, {0x2bbcac0?, 0xc00a8d6390}, {0xc005fcce10, 0x26})
	github.com/libp2p/go-libp2p@v0.24.1/p2p/transport/webtransport/transport.go:135 +0x167
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).dialAddr(0xc0019521a0, {0x2ba5508, 0xc00a8a5ec0}, {0xc005fcce10, 0x26}, {0x2bbcac0?, 0xc00a8d6390})
	github.com/libp2p/go-libp2p@v0.24.1/p2p/net/swarm/swarm_dial.go:493 +0x1f1
github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).executeDial(0xc00071dc70, 0xc00a8a7a80)
	github.com/libp2p/go-libp2p@v0.24.1/p2p/net/swarm/limiter.go:219 +0xf0
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).addCheckFdLimit
	github.com/libp2p/go-libp2p@v0.24.1/p2p/net/swarm/limiter.go:169 +0x4bb
```

The same issue appeared 5 times in two days (running in Docker with `--restart unless-stopped`)

This seems to be different from https://github.com/ipfs/kubo/issues/9515, as i always get the above trace around limiter/transport – filling as a separate issue. 

cc https://github.com/libp2p/go-libp2p/issues/1958

**Comment by marten-seemann** [comment]
I assume you're not using the resource manager? That would explain the nil pointer dereference, as we're not properly initializing the `NullResourceManager` for WebTransport.

**Comment by lidel** [comment]
@marten-seemann no, i get this error WITH resource manager is enabled:

```console
ipfs version 0.18.0-rc1
Found IPFS fs-repo at /data/ipfs
Initializing daemon...
Kubo version: 0.18.0-rc1-ae774a3
Repo version: 13
System version: amd64/linux
Golang version: go1.19.1

Computing default go-libp2p Resource Manager limits based on:
    - 'Swarm.ResourceMgr.MaxMemory': "8.3 GB"
    - 'Swarm.ResourceMgr.MaxFileDescriptors': 524288

Applying any user-supplied overrides on top.
Run 'ipfs swarm limit all' to see the resulting limits.

Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1
....
Daemon is ready
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1b589c7]

goroutine 284534 [running]:
github.com/libp2p/go-libp2p/p2p/transport/webtransport.(*transport).Dial(0xc000736580, {0x2ba5508, 0xc00a8a5ec0}, {0x2bbcac0?, 0xc00a8d6390}, {0xc005fcce10, 0x26})
	github.com/libp2p/go-libp2p@v0.24.1/p2p/transport/webtransport/transport.go:135 +0x167
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).dialAddr(0xc0019521a0, {0x2ba5508, 0xc00a8a5ec0}, {0xc005fcce10, 0x26}, {0x2bbcac0?, 0xc00a8d6390})
	github.com/libp2p/go-libp2p@v0.24.1/p2p/net/swarm/swarm_dial.go:493 +0x1f1
github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).executeDial(0xc00071dc70, 0xc00a8a7a80)
	github.com/libp2p/go-libp2p@v0.24.1/p2p/net/swarm/limiter.go:219 +0xf0
created by github.com/libp2p/go-libp2p/p2p/net/swarm.(*dialLimiter).addCheckFdLimit
	github.com/libp2p/go-libp2p@v0.24.1/p2p/net/swarm/limiter.go:169 +0x4bb
```

**Comment by lidel** [comment]
Was unable to trigger panic so far, assuming https://github.com/ipfs/kubo/pull/9522 fixed it. 
Will observe logs this week and reopen if it happens again.
