### ISSUE TITLE
ci/gh-experiment: sharness fail during sharness-html generation

### ISSUE THREAD

**Issue by lidel** [ipfs/kubo#9551]
Seems that sometimes successful run of sharness tests fail on Github Action due to Java error around  `test/sharness/test-results/sharness.xml`:

https://github.com/ipfs/kubo/actions/runs/3920501209/jobs/6702175413#step:10:70208:
```
*** test/sharness/aggregate ***
fixed   0
success 7711
failed  0
broken  18
total   7751
*** test/sharness/test-results/sharness.xml ***
Exception in thread "main" java.lang.NoClassDefFoundError: org/xmlresolver/Resolver
	at net.sf.saxon.lib.CatalogResourceResolver.<init>(CatalogResourceResolver.java:46)
*** test/sharness/test-results/sharness-html ***
Downloading SaxonHE11-4J.zip
Removing old lib/dependencies/SaxonHE11-4J
Unzipping lib/dependencies/SaxonHE11-4J.zip
	at net.sf.saxon.Configuration.init(Configuration.java:367)
	at net.sf.saxon.Configuration.<init>(Configuration.java:230)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at net.sf.saxon.Configuration.newConfiguration(Configuration.java:246)
	at net.sf.saxon.s9api.Processor.<init>(Processor.java:69)
	at net.sf.saxon.Transform.doTransform(Transform.java:321)
	at net.sf.saxon.Transform.main(Transform.java:81)
Caused by: java.lang.ClassNotFoundException: org.xmlresolver.Resolver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 12 more
make: *** [test/sharness/Rules.mk:52: test/sharness/test-results/sharness-html] Error 1
```

@galargh I had to time to look into this –  assuming you may be better person to diagnose?

**Comment by galargh** [comment]
I think I found it! See https://github.com/ipfs/kubo/pull/9552
